version: '3.4'

services:
  naming-server:
    image: johnwillv/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - curso-udemy
  api-gatway:
    image: johnwillv/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    networks:
      - curso-udemy
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411

  cambio-server:
    image: johnwillv/cambio-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.APPLICATION.NAME: cambio-service
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: gandalf
      SPRING.DATASOURCE.TESTWHILEIDLE: "true"
      SPRING.DATASOURCE.VALIDATIONQUERY: SELECT 1
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: gandalf
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - curso-udemy
  book-server:
    image: johnwillv/book-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3308/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: gandalf
      SPRING.DATASOURCE.TESTWHILEIDLE: "true"
      SPRING.DATASOURCE.VALIDATIONQUERY: SELECT 1
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3308/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: gandalf
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
    networks:
      - curso-udemy
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - curso-udemy
  cambio-db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gandalf
      MYSQL_USER: docker
      MYSQL_PASSWORD: gandalf
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - curso-udemy
  book-db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gandalf
      MYSQL_USER: docker
      MYSQL_PASSWORD: gandalf
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
      TZ: America/Sao_Paulo
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - curso-udemy
networks:
  curso-udemy:
    driver: bridge
