server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
        limit-refresh-period: 10s
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true # fibonacci

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: gandalf
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/book-service?useTimezone=true&serverTimezone=UTC
    user: root
    password: gandalf
sleuth:
  sampler:
    probability: 1
    #probability: 0.05 producao
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
